
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "ddynclk.h"

/*
* The configuration table for devices
*/

DDynClk_Config DDynClk_ConfigTable[XPAR_DDYNCLK_NUM_INSTANCES] =
{
	{
		XPAR_AXI_DYNCLK_0_DEVICE_ID,
		XPAR_AXI_DYNCLK_0_S_AXI_LITE_BASEADDR
	}
};


